/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: alemenemiao (https://sketchfab.com/alemenemiao)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/alien-island-63996e6bdef84edd96715f6295e03688
Title: Alien island
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import { useFrame, useThree } from "@react-three/fiber";

import low_poly_islandScene from "../assets/3d/island_low_poly.glb";

export function ChillIsland({
    isRotating,
    setIsRotating,
    setCurrentStage,
    currentFocusPoint,
    ...props
}) {  
  const islandRef = useRef();
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(low_poly_islandScene);
      // Use a ref for the last mouse x position
      const lastX = useRef(0);
      // Use a ref for rotation speed
      const rotationSpeed = useRef(0);
      // Define a damping factor to control rotation damping
      const dampingFactor = 0.95;
    
      // Handle pointer (mouse or touch) down event
      const handlePointerDown = (event) => {
        event.stopPropagation();
        event.preventDefault();
        setIsRotating(true);
    
    
        // Calculate the clientX based on whether it's a touch event or a mouse event
        const clientX = event.touches ? event.touches[0].clientX : event.clientX;
    
        // Store the current clientX position for reference
        lastX.current = clientX;
      };
    
      // Handle pointer (mouse or touch) up event
      const handlePointerUp = (event) => {
        event.stopPropagation();
        event.preventDefault();
        setIsRotating(false);
      };
    
      // Handle pointer (mouse or touch) move event
      const handlePointerMove = (event) => {
        event.stopPropagation();
        event.preventDefault();
        if (isRotating) {
          // If rotation is enabled, calculate the change in clientX position
          const clientX = event.touches ? event.touches[0].clientX : event.clientX;
    
          // calculate the change in the horizontal position of the mouse cursor or touch input,
          // relative to the viewport's width
          const delta = (clientX - lastX.current) / viewport.width;
    
          // Update the island's rotation based on the mouse/touch movement
          islandRef.current.rotation.y += delta * 0.01 * Math.PI;
    
          // Update the reference for the last clientX position
          lastX.current = clientX;
    
          // Update the rotation speed
          rotationSpeed.current = delta * 0.01 * Math.PI;
        }
      };
    
      // Handle keydown events
      const handleKeyDown = (event) => {
        if (event.key === "ArrowLeft") {
          if (!isRotating) setIsRotating(true);
    
          islandRef.current.rotation.y += 0.01 * Math.PI;
          rotationSpeed.current = 0.0025;
        } else if (event.key === "ArrowRight") {
          if (!isRotating) setIsRotating(true);
    
          islandRef.current.rotation.y -= 0.01 * Math.PI;
          rotationSpeed.current = -0.0025;
        }
      };
    
      // Handle keyup events
      const handleKeyUp = (event) => {
        if (event.key === "ArrowLeft" || event.key === "ArrowRight") {
          setIsRotating(false);
        }
      };
    
      // Touch events for mobile devices
      const handleTouchStart = (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsRotating(true);
      
        const clientX = e.touches ? e.touches[0].clientX : e.clientX;
        lastX.current = clientX;
      }
      
      const handleTouchEnd = (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsRotating(false);
      }
      
      const handleTouchMove = (e) => {
        e.stopPropagation();
        e.preventDefault();
      
        if (isRotating) {
          const clientX = e.touches ? e.touches[0].clientX : e.clientX;
          const delta = (clientX - lastX.current) / viewport.width;
      
          islandRef.current.rotation.y += delta * 0.01 * Math.PI;
          lastX.current = clientX;
          rotationSpeed.current = delta * 0.01 * Math.PI;
        }
      }
    
      useEffect(() => {
        // Add event listeners for pointer and keyboard events
        const canvas = gl.domElement;
        canvas.addEventListener("pointerdown", handlePointerDown);
        canvas.addEventListener("pointerup", handlePointerUp);
        canvas.addEventListener("pointermove", handlePointerMove);
        window.addEventListener("keydown", handleKeyDown);
        window.addEventListener("keyup", handleKeyUp);
        canvas.addEventListener("touchstart", handleTouchStart);
        canvas.addEventListener("touchend", handleTouchEnd);
        canvas.addEventListener("touchmove", handleTouchMove);
    
        // Remove event listeners when component unmounts
        return () => {
          canvas.removeEventListener("pointerdown", handlePointerDown);
          canvas.removeEventListener("pointerup", handlePointerUp);
          canvas.removeEventListener("pointermove", handlePointerMove);
          window.removeEventListener("keydown", handleKeyDown);
          window.removeEventListener("keyup", handleKeyUp);
          canvas.removeEventListener("touchstart", handleTouchStart);
          canvas.removeEventListener("touchend", handleTouchEnd);
          canvas.removeEventListener("touchmove", handleTouchMove);
        };
      }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);
    
      // This function is called on each frame update
      useFrame(() => {
        // If not rotating, apply damping to slow down the rotation (smoothly)
        if (!isRotating) {
          // Apply damping factor
          rotationSpeed.current *= dampingFactor;
    
          // Stop rotation when speed is very small
          if (Math.abs(rotationSpeed.current) < 0.001) {
            rotationSpeed.current = 0;
          }
    
          islandRef.current.rotation.y += rotationSpeed.current;
        } else {
          // When rotating, determine the current stage based on island's orientation
          const rotation = islandRef.current.rotation.y;
    
          /**
           * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
           * The goal is to ensure that the rotation value remains within a specific range to
           * prevent potential issues with very large or negative rotation values.
           *  Here's a step-by-step explanation of what this code does:
           *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
           *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
           *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
           *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
           *     This is done to ensure that the value remains positive and within the range of
           *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
           *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
           *     modulo operation to the value obtained in step 2. This step guarantees that the value
           *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
           *     circle in radians.
           */
          const normalizedRotation =
            ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);
    
          // Set the current stage based on the island's orientation
          switch (true) {
            case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
              setCurrentStage(4);
              break;
            case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
              setCurrentStage(3);
              break;
            case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
              setCurrentStage(2);
              break;
            case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
              setCurrentStage(1);
              break;
            default:
              setCurrentStage(null);
          }
        }
      });
  return (
    // 3D Model from : https://sketchfab.com/3d-models/3d-low-poly-island-d9823aef904045c2aa0a5857d59603f9#download
    <a.group ref={islandRef}{...props}>
       <group scale={0.01}>
        <group
          position={[-173.751, 86.928, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_Skin_0.geometry}
            material={materials.Skin}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_lights_0.geometry}
            material={materials.lights}
          />
        </group>
        <group
          position={[-180.162, 192.51, 8.883]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_Skin_0.geometry}
            material={materials.Skin}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_lights_0.geometry}
            material={materials.lights}
          />
        </group>
        <group
          position={[-173.678, 231.325, 166.04]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_Dark_metal_0.geometry}
            material={materials.Dark_metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_lights_0.geometry}
            material={materials.lights}
          />
        </group>
        <group
          position={[57.96, 115.513, 70.198]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube047_Dark_metal_0.geometry}
            material={materials.Dark_metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube047_lights_0.geometry}
            material={materials.lights}
          />
        </group>
        <group
          position={[0, -185.927, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Light_brown_0.geometry}
            material={materials.Light_brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Mid_brown_0.geometry}
            material={materials.Mid_brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Dark_Brown_0.geometry}
            material={materials.Dark_Brown}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_Blue_0.geometry}
          material={materials.Blue}
          position={[97.56, 1.346, 159.579]}
          rotation={[-1.417, 0.144, 0.068]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Yellow_0.geometry}
          material={materials.Yellow}
          position={[-173.751, 78.479, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_Yellow_0.geometry}
          material={materials.Yellow}
          position={[-180.162, 192.51, 8.883]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-173.365, 257.786, -0.168]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-178.898, 320.003, 8.68]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-169.056, 135.908, 114.018]}
          rotation={[-Math.PI / 2, -0.017, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-172.595, 198.83, 117.507]}
          rotation={[-1.66, 0.001, -0.013]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-202.099, 185.864, 115.184]}
          rotation={[-Math.PI / 2, -1.336, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-139.235, 176.503, 119.473]}
          rotation={[-1.553, 1.336, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-194.717, 158.205, 119.068]}
          rotation={[-Math.PI / 2, 1.336, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-116.719, 73.453, 96.581]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-230.101, 73.331, 93.95]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-115.292, 75.348, -106.271]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-230.101, 73.331, -109.092]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-119.55, 201.296, 39.823]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-113.375, 263.862, 25.653]}
          rotation={[-2.383, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-172.918, 125.609, -117.909]}
          rotation={[-1.759, -0.179, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-172.595, 198.83, -116.038]}
          rotation={[-1.659, 0.005, -0.06]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-202.099, 185.864, -117.362]}
          rotation={[-Math.PI / 2, -1.336, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-139.235, 176.503, -115.217]}
          rotation={[-Math.PI / 2, 1.336, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-173.751, 86.928, -4.224]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-173.751, 86.928, -1.691]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-180.162, 192.51, 8.883]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-173.751, 86.928, 5.604]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-173.751, 86.928, 11.391]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-192.095, 52.887, 93.134]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-153.356, 79.06, 95.998]}
          rotation={[-1.281, 0.009, 0.03]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-153.356, 80.778, 96.427]}
          rotation={[-1.187, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-175.993, 172.829, 118.377]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-175.993, 172.826, 118.758]}
          rotation={[-1.491, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032__0.geometry}
          material={materials["Cube.032__0"]}
          position={[-175.802, 223.636, 118.567]}
          rotation={[-Math.PI, 0, 1.651]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-113.555, 232.768, 8.999]}
          rotation={[-Math.PI / 2, 0, 1.564]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-113.092, 231.619, 8.756]}
          rotation={[-Math.PI, 0, 1.618]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-168.449, 162.907, -117.071]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-168.449, 162.08, -117.452]}
          rotation={[1.566, -Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube037_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-227.999, 231.865, 0.095]}
          rotation={[-Math.PI / 2, 0, 1.564]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-228.795, 230.919, -0.105]}
          rotation={[-Math.PI, 0, 1.532]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-172.716, 79.129, -107.25]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-172.716, 79.542, -107.631]}
          rotation={[1.566, -Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[-192.095, 53.494, 91.567]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube042_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-193.565, 81.817, 99.071]}
          rotation={[-1.145, -0.07, -0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-191.802, 50.408, 90.029]}
          rotation={[-1.474, -0.16, 0.027]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_Dark_metal_0.geometry}
          material={materials.Dark_metal}
          position={[-95.188, 148.797, -92.696]}
          rotation={[-Math.PI / 2, 0.227, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-112.699, 73.453, -7.329]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-234.121, 73.331, -9.96]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube046_Brown_Refinado_0.geometry}
          material={materials.Brown_Refinado}
          position={[-114.959, 221.722, 39.823]}
          rotation={[-0.411, -0.092, -0.04]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_Dark_metal_0.geometry}
          material={materials.Dark_metal}
          position={[-173.22, 249.63, 166.6]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[55.212, 72.696, 43.934]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_Dark_metal_0.geometry}
          material={materials.Dark_metal}
          position={[57.987, 133.659, 70.488]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001_Dark_Brown_0.geometry}
          material={materials.Dark_Brown}
          position={[-182.654, 66.047, 94.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Dark_Brown_0.geometry}
          material={materials.Dark_Brown}
          position={[252.382, 13.87, -102.199]}
          rotation={[-1.643, 0.239, 0.04]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002_Three_3_0.geometry}
          material={materials.Three_3}
          position={[289.418, 94.021, -108.01]}
          rotation={[-2.754, -0.857, -0.36]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003_Three_1_0.geometry}
          material={materials.Three_1}
          position={[250.278, 102.85, -121.959]}
          rotation={[0.108, -0.324, 1.777]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004_Three_2_0.geometry}
          material={materials.Three_2}
          position={[253.697, 96.72, -81.31]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere005_Three_1_0.geometry}
          material={materials.Three_1}
          position={[279.476, 127.995, -95.15]}
          rotation={[2.856, 0.748, 1.299]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere006_Three_3_0.geometry}
          material={materials.Three_3}
          position={[242.098, 139.361, -105.863]}
          rotation={[1.142, -0.346, 2.12]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere008_Three_3_0.geometry}
          material={materials.Three_3}
          position={[275.625, 166.55, -123.173]}
          rotation={[2.995, -1.054, -2.097]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere009_Three_1_0.geometry}
          material={materials.Three_1}
          position={[262.914, 160.559, -104.896]}
          rotation={[1.429, -0.635, 1.073]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere010_Three_1_0.geometry}
          material={materials.Three_1}
          position={[254.098, 165.373, -126.879]}
          rotation={[1.345, 0.269, 1.956]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere011_Three_2_0.geometry}
          material={materials.Three_2}
          position={[259.763, 181.476, -130.819]}
          rotation={[-3.132, -1.042, 0.49]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere007_Three_2_0.geometry}
          material={materials.Three_2}
          position={[266.203, 104.521, -138.355]}
          rotation={[-3.132, -1.042, 0.49]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Brown_0.geometry}
          material={materials.Brown}
          position={[122.464, 46.963, -53.977]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere034_Stone__3_0.geometry}
          material={materials.Stone__3}
          position={[177.202, 16.806, 97.182]}
          rotation={[2.525, -1.189, 0.214]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_Material_0.geometry}
          material={materials.Material}
          position={[-197.757, 22.437, 130.164]}
          rotation={[-1.451, -0.127, -1.264]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-159.488, 24.108, 145.793]}
          rotation={[-1.451, -0.127, -0.853]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-199.667, 15.389, 167.31]}
          rotation={[-1.451, -0.127, 0.279]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_Material_0.geometry}
          material={materials.Material}
          position={[-191.606, 9.063, 203.34]}
          rotation={[-1.294, -0.225, -2.127]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-168.102, 9.378, 229.104]}
          rotation={[-1.303, -0.272, -0.23]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_Material_0.geometry}
          material={materials.Material}
          position={[-205.728, -1.901, 235.019]}
          rotation={[-1.303, -0.272, -1.994]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-185.48, -6.598, 275.217]}
          rotation={[-1.32, -0.274, 2.575]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_Material_0.geometry}
          material={materials.Material}
          position={[-218.287, -20.975, 290.072]}
          rotation={[-1.32, -0.274, -1.491]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_Material_0.geometry}
          material={materials.Material}
          position={[-159.881, 19.44, 184.289]}
          rotation={[-1.451, -0.127, -2.627]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_Green_plant_3_0.geometry}
          material={materials.Green_plant_3}
          position={[83.464, -4.128, 222.572]}
          rotation={[-1.417, 0.116, -0.005]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Green_plant_3_0.geometry}
          material={materials.Green_plant_3}
          position={[54.759, 3.102, 200.025]}
          rotation={[-1.389, 0.148, -1.902]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_Green_plant_3_0.geometry}
          material={materials.Green_plant_3}
          position={[130.017, -10.976, 214.929]}
          rotation={[-1.386, 0.142, 2.26]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_Green_plant_3_0.geometry}
          material={materials.Green_plant_3}
          position={[95.474, -1.592, 194.589]}
          rotation={[-1.389, 0.126, -2.829]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere038_Smoke_0.geometry}
          material={materials.Smoke}
          position={[-71.36, 324.269, -80.303]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere039_Smoke_0.geometry}
          material={materials.Smoke}
          position={[-84.442, 354.851, -77.597]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere040_Smoke_0.geometry}
          material={materials.Smoke}
          position={[-54.287, 394.103, -74.591]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere041_Smoke_0.geometry}
          material={materials.Smoke}
          position={[-91.822, 464.666, -76.028]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere042_Smoke_0.geometry}
          material={materials.Smoke}
          position={[-35.733, 555.76, -57.137]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere_Pink_0.geometry}
          material={materials.Pink}
          position={[130.749, 162.797, -55.182]}
          rotation={[-Math.PI / 2, 0.072, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane025_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[130.229, 34.496, 68.301]}
          rotation={[-1.486, -0.194, -0.617]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[130.229, 34.496, 68.301]}
          rotation={[-1.195, 0.003, -1.821]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[130.229, 34.496, 68.301]}
          rotation={[-1.13, -0.173, -2.578]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[130.229, 34.496, 68.301]}
          rotation={[-1.183, -0.009, 2.036]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[130.229, 34.496, 68.301]}
          rotation={[-1.207, 0.102, -3.112]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[128.478, 36.043, 70.987]}
          rotation={[-1.331, 0.243, -2.554]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[128.471, 36.712, 71.26]}
          rotation={[-0.978, -0.048, 1.325]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[128.478, 36.043, 70.987]}
          rotation={[-1.67, -0.251, -1.262]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[128.478, 36.043, 70.987]}
          rotation={[-1.291, -0.05, -1.437]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034_Green_Plant_0.geometry}
          material={materials.Green_Plant}
          position={[128.478, 36.043, 70.987]}
          rotation={[-1.099, 0.134, 2.556]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[23.08, 33.346, 157.379]}
          rotation={[-3.101, -0.368, 3.121]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[29.833, 39.824, 139.662]}
          rotation={[-3.101, -0.368, 3.121]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[29.763, 26.435, 149.208]}
          rotation={[-3.101, -0.368, 3.121]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[22.466, 24.16, 144.561]}
          rotation={[-3.101, -0.368, 3.121]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[37.251, 33.476, 109.002]}
          rotation={[0.041, 0.368, 0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[29.567, 32.889, 126.965]}
          rotation={[0.041, 0.368, 0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[33.007, 30.55, 116.579]}
          rotation={[0.041, 0.368, 0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[38.249, 23.123, 120.872]}
          rotation={[0.041, 0.368, 0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[50.691, 32.914, 126.015]}
          rotation={[0.041, 0.368, 0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[43.007, 32.327, 143.978]}
          rotation={[0.041, 0.368, 0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[46.446, 29.987, 133.592]}
          rotation={[0.041, 0.368, 0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[51.688, 22.561, 137.885]}
          rotation={[0.041, 0.368, 0.021]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[54.612, 39.716, 107.968]}
          rotation={[-3.084, 0.852, 3.062]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[45.62, 26.327, 111.172]}
          rotation={[-3.084, 0.852, 3.062]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[66.005, 29.879, 121.497]}
          rotation={[0.058, -0.852, 0.079]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024_Green_plant_2_0.geometry}
          material={materials.Green_plant_2}
          position={[63.767, 22.452, 127.893]}
          rotation={[0.058, -0.852, 0.079]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_Green_1_0.geometry}
          material={materials.Green_1}
          position={[0, 7.263, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere012_Stone_1_0.geometry}
          material={materials.Stone_1}
          position={[260.235, -29.882, 262.068]}
          rotation={[-1.907, 0.678, -1.562]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere013_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[166.968, -183.414, 235.324]}
          rotation={[-1.907, 0.678, -1.562]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere014_Stone__3_0.geometry}
          material={materials.Stone__3}
          position={[39.334, -309.025, 255.644]}
          rotation={[-1.907, 0.678, -1.562]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere015_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[-320.68, 5.746, 125.094]}
          rotation={[-1.907, 0.678, -1.562]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere016_Stone__3_0.geometry}
          material={materials.Stone__3}
          position={[-252.214, 5.363, 116.419]}
          rotation={[2.721, -0.819, 3.073]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere017_Stone__3_0.geometry}
          material={materials.Stone__3}
          position={[-208.048, -211.139, 177.181]}
          rotation={[2.255, 0.988, 0.333]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere018_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[-312.66, -149.496, -41.851]}
          rotation={[2.386, -0.284, -1.999]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere019_Stone_1_0.geometry}
          material={materials.Stone_1}
          position={[-310.634, -28.149, -196.016]}
          rotation={[-1.307, 0.665, -1.845]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere020_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[-0.091, 51.591, -165.764]}
          rotation={[-1.973, 0.548, -2.69]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere021_Stone_1_0.geometry}
          material={materials.Stone_1}
          position={[280.148, -34.451, -226.386]}
          rotation={[1.073, -0.017, 0.029]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere022_Stone__3_0.geometry}
          material={materials.Stone__3}
          position={[-130.025, -317.136, -229.356]}
          rotation={[-2.414, -0.957, 1.941]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere023_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[11.358, -26.962, -327.754]}
          rotation={[-0.2, 0.866, 2.936]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere024_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[171.2, -277.244, -184.998]}
          rotation={[-0.2, 0.866, 2.936]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere025_Stone__3_0.geometry}
          material={materials.Stone__3}
          position={[290.586, -213.376, -3.536]}
          rotation={[-0.2, 0.866, 2.936]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere026_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[193.631, 8.849, 122.078]}
          rotation={[-3.132, -1.042, 0.49]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere027_Stone__3_0.geometry}
          material={materials.Stone__3}
          position={[220.856, 19.841, 67.541]}
          rotation={[2.602, -0.381, 1.693]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere028_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[252.97, 7.218, 108.809]}
          rotation={[1.385, -0.113, 1.894]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere029_Stone_1_0.geometry}
          material={materials.Stone_1}
          position={[-51.73, -113.352, -312.404]}
          rotation={[-2.576, -0.414, 2.817]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere030_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[297.261, -113.707, -105.553]}
          rotation={[-1.819, -0.41, -2.678]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere031_Stone_1_0.geometry}
          material={materials.Stone_1}
          position={[41.596, -162.198, 301.196]}
          rotation={[2.26, -0.579, -2.198]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere032_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[-115.944, -251.176, 248.608]}
          rotation={[-0.995, -0.966, -2.714]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere033_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[-99.219, -88.229, 349.355]}
          rotation={[-3.132, -1.042, 0.49]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere035_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[170.126, 36.792, 71.048]}
          rotation={[-1.144, 0.504, -0.275]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere036_Stone_2_0.geometry}
          material={materials.Stone_2}
          position={[191.061, 45.716, 43.899]}
          rotation={[1.482, 1.181, -0.649]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere037_Stone__3_0.geometry}
          material={materials.Stone__3}
          position={[193.743, -3.347, 216.096]}
          rotation={[-1.907, 0.678, -1.562]}
          scale={100}
        />
      </group>
    </a.group>
  );
}
